name: SuiteCloudPOC CLI
on:
  workflow_dispatch:
  
jobs:
  deploy-production:
    environment: production
    name: Deploy to Production (main)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g --acceptSuiteCloudSDKLicense @oracle/suitecloud-cli
      - run: |
          cd ./com.servicerocket.clipoc
      - run: suitecloud account:savetoken ${{secrets.NS_TOKEN_ID}} --tokensecret ${{secrets.NS_TOKEN_SECRET}}
