name: SuiteCloudPOC CLI
on:
  workflow_dispatch:
  
jobs:
  deploy-production:
    environment: production
    name: Deploy to Production (main)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd ./com.servicerocket.clipoc/src
          npm install
          npm install -g --acceptSuiteCloudSDKLicense @oracle/suitecloud-cli
          suitecloud account:savetoken -authid myDevRole -tokenid ${{secrets.NS_TOKEN_ID}} -tokensecret ${{secrets.NS_TOKEN_SECRET}}
          suitecloud account:deploy
