name: SuiteCloudPOC CLI
on:
  workflow_dispatch:
  
jobs:
  deploy-production:
    environment: production
    name: Deploy to Production (main)
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g --acceptSuiteCloudSDKLicense @oracle/suitecloud-cli
      - run: suitecloud account:savetoken ${{secrets.NS_TOKEN_ID}} --tokensecret ${{secrets.NS_TOKEN_SECRET}}
